Makefile

prepushターゲットを移動

---

.gitignore
man/accept.txt
man/bind.txt
man/curl.txt
man/listen.txt
man/protocols.txt
man/select.txt
man/setsockopt.txt
man/socket.txt

個人的に使っているものでしたが、参考になるかもなので、pushします。

manをドキュメントとして

---

.github/pre-push

srcs, includesのサブディレクトリ内のファイルを引数として渡すよう変更しました。

prepushの引数修正

---

.gitignore

gitignore memo

---

googletest/tests/response.cpp
includes/Response.hpp
srcs/Response.cpp
srcs/server.cpp

#82 が終わればプルリク出します。
vectorをmapにしてみました.
こっちの方が見やすければ承認お願いします.

レスポンスクラスの整理

---

includes/Webserv.hpp
includes/message.hpp
srcs/main.cpp
srcs/message/response_message.cpp
srcs/server.cpp

私が作った関数でも遠慮しないでどんどん編集してもらって構いません。関数の場所が命名に沿ってなかったので、移動させました。

refactor: 関数を整理

---

googletest/tests/token_test.cpp

僕が勝手にしたテストなので, 主旨に沿っていたら使ってください

tokens_test追加

---

googletest/tests/http_test.cpp
html/bad_request.html
html/forbidden.html
html/internal_server_error.html
html/not_implemented.html
html/unknown_error.html
includes/http.hpp
srcs/http/http.cpp
srcs/http/method.cpp
srcs/http/request.cpp
srcs/http/response.cpp

requestをmapで持っていたのを構造体に変更

---

includes/http.hpp
srcs/http/method.cpp
srcs/http/response.cpp

@nakamo326 書き換えてみたけど、response_messageに持たせるのも、それはそれで微妙という感じになった。難しいね

response_messageにpathを保持するようにしてみた

---

includes/Webserv.hpp
includes/event.hpp
includes/http.hpp
includes/socket.hpp
srcs/ServerConfig.cpp
srcs/create_server_group.cpp
srcs/http/http.cpp
srcs/http/method.cpp
srcs/http/request.cpp
srcs/http/response.cpp
srcs/listen_event.cpp
srcs/main.cpp
srcs/read_config.cpp
srcs/socket.cpp
srcs/tokenize.cpp
srcs/util.cpp

ヘッダーインクルード修正

---

includes/http.hpp
includes/request_parse.hpp
srcs/http/request.cpp
srcs/http/request_parse.cpp

POST時のbodyのパース。イメージしにくかったので実装してみました。
一回の読み取りで、読み取りきらないパターンがあると想定するなら、パースのタイミングは、ファイル読み取りが最後まで読み取り終わったときがトリガーになってパースする感じ???
テストしたい関数がstaticになっているので、goでpostのパターンもテストできるようになったらテスト書きます。

bodyのparse

---

html/post_form.html
html/thanks.html

仕様確認に使っていたものです
他にも追加したい要素とかあれば教えてください。

post用htmlを追加

---

googletest/tests/server_config_test.cpp
srcs/config/ServerConfig.cpp
srcs/config/ServerConfig.hpp
srcs/config/read_config.cpp
srcs/http/request.cpp
srcs/http/request_parse.cpp
srcs/http/request_parse.hpp
srcs/util/tokenize.hpp

よく使うものはtypedefを入れていこうというという話があったので変えました

typedef でtoken_vector

---

googletest/tests/http_test.cpp
googletest/tests/util_test.cpp
srcs/config/ServerConfig.cpp
srcs/http/method/method.cpp
srcs/http/response/response.cpp
srcs/utils/config_parser_utils.cpp
srcs/utils/config_parser_utils.hpp
srcs/utils/file_io_utils.cpp
srcs/utils/file_io_utils.hpp
srcs/utils/http_parser_utils.cpp
srcs/utils/http_parser_utils.hpp

GETメソッドから共通で利用できる部分を切り出しました。
その他細かい変更を加えています。
#211 の一部を切り出したものになります。先にこちらから確認お願いします。

http_utils追加

---

googletest/tdata/sample.conf
googletest/tests/server_config_test.cpp
srcs/config/create_server_group.cpp

ホスト、ポート、サーバー名が同じ設定をserver_groupに加えないよう関数を追加しました。

server_name重複除外

---

srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Request.cpp
srcs/event/Request.hpp
srcs/event/connection_handler.cpp
srcs/event/connection_handler.hpp
srcs/event/listen_event.cpp
srcs/http/HttpMessage.hpp

connection_handler, Connection, Request間の処理を整理してクラスにしました。
#248 , #241 の後で大丈夫です。

Connection、Requestをクラスへ変更

---

integration_test/client.go
integration_test/test_IOMULT.go
integration_test/test_utils.go

ミーティングでお話しします。
clientストラクトを作ってテストするようにしました。
他のテストもこっち使った方がリクエスト文字列を自由に用意できるのでいいかもしれません。

integration_testリファクタ

---

srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp
srcs/event/connection_handler.cpp

RequestクラスをTransactionクラスに変更

---

srcs/config/Socket.cpp
srcs/config/Socket.hpp
srcs/config/SocketOpener.cpp
srcs/config/SocketOpener.hpp
srcs/config/create_listen_fd_map.cpp

socketクラスを関数オブジェクトに変更し、addrinfoを引数にfdを返すよう変更しました。
名前の変更は仮なのでいい案あったら教えてください。

socketクラスを関数オブジェクトに変更

---

srcs/http/response/Response_cgi.cpp

refactor/parse_post_body add: vector_to_array

---

googletest/tests/util_test.cpp
srcs/http/response/Response.cpp
srcs/http/response/Response.hpp
srcs/utils/utils.cpp
srcs/utils/utils.hpp

ファイルパスのエラーが、request内で行われる変更に向けてis_minus_depthを移動させました。
ファイルパスを受け取ってboolを返すようにシグニチャーも変更しました。
コメントアウトされていたテストも戻しました。

move is_minus_depth

---

integration_test/tester/utils.go
integration_test/tests/DELETE.go
integration_test/tests/GET.go
integration_test/tests/IOMULT.go
integration_test/tests/POST.go
integration_test/tests/utils.go

テスト実行時のメッセージをtest_handler()で自動で出力するように変更しました

呼び出し関数の名前をテスト時に出力

---

integration_test/main.go
integration_test/runWebserv.go
integration_test/tester/utils.go

色々タイムアウトが出てきそうなので, テスト全体でタイムアウトについて考慮する設計に変えました。
また問題が出たら対応していこうかと思っています。

itest 全体でタイムアウトするように変更

---

.github/pre-push
srcs/event/Connection.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp
srcs/http/response/Response_autoindex.cpp

chunkをhandle_requestから切り出しました。

chunkの処理をhandle_requestから切り出し

---

srcs/config/Config.cpp
srcs/config/Config.hpp

__set_getaddrinfo をstaticに

---

srcs/event/Server.cpp
srcs/event/Server.hpp

__add_listenfd_to_pollfds、__add_connfd_to_pollfdsのシグニチャーを変更しました。
何からpollfdsを取り出し入れるのか、明確にした感じです。

__add_listenfd_to_pollfds, __add_connfd_to_pollfdsのシグニチャーを変更

---

integration_test/main.go
integration_test/tester/client.go
integration_test/tests/TestAutoindex.go
integration_test/tests/TestBadRequest.go
integration_test/tests/TestCgi.go
integration_test/tests/TestDELETE.go
integration_test/tests/TestIOMulti.go
integration_test/tests/TestLimitExpect.go
integration_test/tests/TestLocation.go
integration_test/tests/TestServerName.go
integration_test/tests/generate.go
integration_test/tests/testGET.go
integration_test/tests/types.go
integration_test/tests/utils.go
integration_test/webserv/kill.go
integration_test/webserv/restart.go

- エラー時は全てexitするように変更
- いらなくなった変数を削除
- エラー時の終了のみwebserv側の出力を表示するように変更

itest, エラー時はexitする

---

integration_test/tester/client.go
integration_test/tests/TestAutoindex.go
integration_test/tests/TestBadRequest.go
integration_test/tests/TestCgi.go
integration_test/tests/TestDELETE.go
integration_test/tests/TestIOMulti.go
integration_test/tests/TestLimitExpect.go
integration_test/tests/TestLocation.go
integration_test/tests/TestServerName.go
integration_test/tests/testGET.go

多数のクライアントからの接続を確かめるテストを追加しました。
その過程で, tester.NewClientを少し変更していますが特に大きな意味はありません。

itest, 多重IOテスト

---

.github/pre-push

clang-tidyコマンドを変更

---

client.cpp
srcs/socket/ClientSocket.cpp
srcs/socket/ClientSocket.hpp
srcs/socket/Timeout.hpp

ClientSocketクラスにあったタイムアウトの機能をクラスにしました。

Timeoutクラス

---

googletest/tests/config_test.cpp
googletest/tests/server_config_test.cpp
googletest/tests/util_test.cpp
srcs/config/Config.cpp
srcs/config/Config.hpp
srcs/config/ConfigGroup.cpp
srcs/config/ConfigGroup.hpp
srcs/socket/ListenSocket.cpp
srcs/socket/ListenSocket.hpp
srcs/utils/utils.cpp

remove socketaddrinfo

---

srcs/socket/ClientSocket.cpp

POLLHUP,POLLERRのチェック

---

srcs/event/Request.cpp
srcs/http/request/RequestInfo.hpp
srcs/http/request/RequestInfo_startline.cpp

remove: check_first_multi_blank_line

---

googletest/tests/config_test.cpp
googletest/tests/util_test.cpp
integration_test/tests/TestBadRequest.go
srcs/config/Config.cpp
srcs/http/request/RequestInfo_header.cpp
srcs/utils/utils.cpp
srcs/utils/utils.hpp

ライブラリの関数を使っていた場所にバリデーションを追加しました。

stringからsize_tのパース

---

srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp
srcs/socket/ClientSocket.cpp

現状akiyamaさんが変更している部分に関わるので、入り口の部分のみ変更しました。

ResponseGeneratorをインスタンスを生成するように変更

---

srcs/http/response/ResponseGen_message.cpp
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp

_create_response_messageをファイルに分割しました

---

srcs/event/Request_tmp.cpp
srcs/http/request/RequestInfo.hpp
srcs/http/response/CgiEnviron.cpp
srcs/http/response/CgiEnviron.hpp
srcs/http/response/ResponseGen_autoindex.cpp
srcs/http/response/ResponseGen_cgi.cpp
srcs/http/response/ResponseGen_message.cpp
srcs/http/response/ResponseGen_method.cpp
srcs/http/response/ResponseGenerator.hpp

ひとまずtarget_pathを作る処理をhandle_methodの中へ移動する変更のみ行いました。
それに伴い, 引数でtarget_pathを渡すようにしてます。

target_pathをrequest_infoから削除しました

---

nginxtest/conf/autoindex.conf
nginxtest/conf/errpage.conf
nginxtest/run.sh
nginxtest/test.sh

nginxのテスト追加

---

srcs/http/response/ResponseGen_method.cpp
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp

テストを通るようなプルリク

---

srcs/event/Response.hpp
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp
srcs/http/response/create_content.cpp
srcs/socket/ClientSocket.cpp
srcs/socket/FileWriteSocket.cpp
srcs/socket/FileWriteSocket.hpp

文字は用意されたものを分割せずに一気に書き込んでいます。
優先度的に高いCGIを先に終わらせたいです。

Filewritesocket

---

srcs/socket/FileReadSocket.hpp
srcs/socket/FileWriteSocket.hpp

デストラクタにvirtual追加

---

html/time_out.py
integration_test/tests/TestCgi.go
srcs/http/response/ResponseGen_create_content.cpp
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp
srcs/socket/CgiSocket.cpp
srcs/socket/CgiSocket.hpp
srcs/socket/ClientSocket.cpp
srcs/socket/ClientSocket.hpp
srcs/socket/FileReadSocket.cpp
srcs/socket/FileReadSocket.hpp
srcs/socket/FileWriteSocket.cpp
srcs/socket/FileWriteSocket.hpp
srcs/socket/ListenSocket.hpp
srcs/socket/LocalIOSocket.cpp
srcs/socket/LocalIOSocket.hpp
srcs/socket/SocketBase.hpp
srcs/socket/SocketMap.cpp

ローカルの入出力を受け取るSocketで共通する処理をまとめたLocalIOSocketクラスを追加しました。

LocalIOSocket追加

---

srcs/http/response/ResponseGen_method.cpp
srcs/http/response/ResponseInfo.cpp
srcs/http/response/ResponseInfo.hpp
srcs/http/response/cgi.cpp
srcs/socket/CgiSocket.cpp
srcs/socket/FileWriteSocket.cpp

ResponseInfoのコンストラクタを使用するよう変更しました。

マージで消えていたコード復活

---

bad_client_test.sh

testスクリプト修正

---

srcs/socket/CgiSocket.cpp
srcs/socket/CgiSocket.hpp
srcs/socket/FileReadSocket.hpp
srcs/socket/FileWriteSocket.cpp
srcs/socket/FileWriteSocket.hpp
srcs/socket/LocalIOSocket.cpp
srcs/socket/LocalIOSocket.hpp

LocalIOSocketにファイル書き込みの処理を共通のメソッドとして実装しました。

ローカルファイル出力共通化

---

html/cgi_test/error/redirect_loop.py
integrationtest/tests/TestCgi.go
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp
srcs/http/response/ResponseInfo.cpp
srcs/socket/CgiSocket.cpp

cgiのローカルリダイレクトでリダイレクトできる回数の上限を追加しました。

ローカルリダイレクト回数制限追加
