.clang-format
Makefile
pre-push
srcs/main.cpp

clang-tidyにincludeのオプションを追加しています。
prepushが最後のコマンドの終了ステータスだけを確認していたのを変更しました。
あと自分のためにlinux用の条件分け追加しています。

prepush hook変更

---

srcs/server.cpp

macのosをアップデートしたら5000がシステムコントロールに使われていたので

使用ポートを5001番でお願いします！

---

srcs/http/method.cpp
srcs/http/response.cpp

nakamotoさんとohkuboさんのやりとりを見たり話を聞いて考えたものをまとめてみたので,  出しておきます！
参考程度で見てみてください。
変えたところ
- bad requestに対する処理は個別にしました
- set_url()関数でしていた処理を分解しました
- request_messageはあくまで参照対象になるよう, target_urlというローカル変数を用意しました
プルリクの範囲を超えるため加えなかったところ
- パース時のエラーをrequest_message.status以外の方法を使って伝えたい

response_messageにpathを持たせる構造をさらにリファクタしてみました

---

googletest/tests/server_config_test.cpp
includes/ServerConfig.hpp
srcs/create_server_group.cpp
srcs/listen_event.cpp

listen_event関数に渡すコンテナ内に保持していたServerConfigをポインタへ変更しました。
#178 への対応です。

コンテナでポインタを保持するように変更

---

googletest/tests/read_config_test.cpp
googletest/tests/server_config_test.cpp
srcs/config/ServerConfig.hpp
srcs/config/create_server_group.cpp
srcs/config/read_config.hpp
srcs/webserv.cpp

read_config.hppをインクルードする場所は必ずServerConfig.hppもインクルードするのでまとめました。

read_config.hppをServerConfig.hppへ統合

---

googletest/tests/http_test.cpp
googletest/tests/read_config_test.cpp
googletest/tests/server_config_test.cpp
googletest/tests/util_test.cpp
srcs/config/Config.cpp
srcs/config/Config.hpp
srcs/config/config_parser_utils.cpp
srcs/config/create_listen_fd_map.cpp
srcs/config/create_listen_fd_map.hpp
srcs/config/open_new_socket.cpp
srcs/config/read_config.cpp
srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Server.cpp
srcs/event/Server.hpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp
srcs/http/http_parser_utils.cpp
srcs/http/method/delete_method.cpp
srcs/http/method/get_method.cpp
srcs/http/request/RequestInfo.hpp
srcs/http/request/RequestInfo_body.cpp
srcs/http/request/RequestInfo_header.cpp
srcs/http/response/cgi.cpp
srcs/http/response/response.cpp
srcs/utils/file_io_utils.cpp
srcs/utils/syscall_wrapper.cpp
srcs/utils/syscall_wrapper.hpp
srcs/utils/tokenize.hpp
srcs/webserv.cpp

int -> conn_fd
の流れで
今まで `int conn_fd`という宣言をしていたところが、変数名とかぶってしまったため
connFdという変数名に変更しました。
他の`typedef`している変数名も同じルールを適応させ 頭文字小文字のキャメルケースに変更しています。
その他にも型名と変数名を揃える変更を行っています。

typename, includeの整理

---

srcs/http/response/Response.cpp
srcs/http/response/Response.hpp

init_response_status_maps()をmain関数などで呼ぶか、ファイル内の関数で初期化する形のどちらかがいいと思いました。

グローバルのmapの初期化

---

googletest/tests/transaction_test.cpp
srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Server.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp

ソケットから受け取ったデータを処理し終わった後にレスポンスの生成を行っていたのを変更して、リクエストが完成するごとにレスポンスを生成するよう変更しました。

pendingを経由しないように変更

---

srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Server.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp

あくまで案です。
ステータスに当たるものが、複数あるので一意にわかるものへ変更
is_send_completedだと、相手から受信完了のものも受け取ったニュアンスがあるので、とりあえずこちらから送っただけというニュアンスで、is_send_allはどうでしょう?
今、連続でリファクタリングが走っていて、現状なにの引数を持っているのか、読んでいて勘違いしそうだったので
pop_front_queueからpop_front_transaction_queueにしました。
一旦冗長に書いて、後で変更が落ち着いてきたら、冗長さを見直してもよいかもと思いました。

refactor/fix_create_transaction 命名案

---

srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Server.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp

ConnectionがTransactionのstateを確認してTransactionのメソッド呼び出していた部分を、Transaction自身が管理するように変更しました。
併せてTransactionクラスの名前を変更する前から残っていた関数名を修正しています。

stateの管理をTransactionへ移動

---

srcs/http/const/const_http_enums.hpp
srcs/http/request/RequestInfo.hpp
srcs/http/request/RequestInfo_body.cpp
srcs/http/request/RequestInfo_header.cpp

#284 に対する別案です。  
content-typeに関して, enumやパース関数を用意してましたがコードが冗長にも思えたのでなしバージョンを書きました。
どちらが良いと思いますか？

content-typeのパースを削除

---

googletest/tests/request_header_parse_test.cpp
googletest/tests/request_parse_test.cpp
googletest/tests/transaction_test.cpp
integration_test/main.go
integration_test/tester/utils.go
integration_test/tests/DELETE.go
integration_test/tests/GET.go
integration_test/tests/IOMULT.go
integration_test/tests/utils.go
srcs/event/Connection.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp
srcs/http/request/RequestInfo.hpp
srcs/http/request/RequestInfo_body.cpp
srcs/http/request/RequestInfo_header.cpp
srcs/http/request/RequestInfo_startline.cpp
srcs/http/response/Response_delete.cpp

012570d parse_start_line,parse_header,parse_body,detect_configをプライベート関数に変更
5083fd6 is_expected_bodyを直接変数を見るように変更
9562347 __get_body_size関数を変数を直接見るように変更
19b6dd3 is_close関数を変数を参照するように変更
is_close()を関数でラップするのではなく、__request_info_.is_close_という形で参照するようにしました。変数名自体が状態を示しているので、関数化する必要がないと判断しました。
f443334 不要な変数への代入を消去
2fada26 get_transaction_stateを使ってステータスを取得するように変更
is_send()という関数は何を持って判断しているのか、分かりづらいと感じたので、ステータスを取ってきて判断するように変更しました。

[review]リクエストライン、ヘッダーのパースを一行ずつに変更 

---

srcs/event/Server.cpp

listenソケットか否かの判定の結果をboolの変数に格納するように変更しました。
また変数名からその値が何を示しているのか判断できるように変数名も変更しています。

intの変数をboolへ変更

---

googletest/tests/transaction_test.cpp
srcs/event/Connection.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp

conn_fdの管理をConnectionがやっているとすれば、connfdに紐づくrequest、responseをConnectionにもたせて、transactionは中間の処理を担うのが適切なようにも思えていますが、後日、図を作ったときにここらへんの話を整理したいです。

get_proper_configをstaticへ

---

html/server_name/dir1/index.html
html/server_name/dir2/index.html
html/server_name/index.html
integration_test/conf/server_name.conf
integration_test/main.go
integration_test/tests/Server_name.go

hostとserver_nameが同じserver設定を使用しているか確認するテストを追加しました。
一致しないときは最初の設定が使用されます。
他に確認が必要な項目があったら連絡ください。

Server_name test追加

---

googletest/tests/request_chunked_test.cpp
googletest/tests/request_parse_test.cpp
googletest/tests/transaction_test.cpp
integration_test/tests/BADREQ.go
srcs/config/Config.cpp
srcs/event/Connection.cpp
srcs/event/Transaction.cpp
srcs/event/Transaction.hpp
srcs/http/const/const_http_enums.hpp
srcs/http/request/RequestInfo.cpp
srcs/http/request/RequestInfo.hpp
srcs/http/request/RequestInfo_header.cpp

bodyのサイズが指定したサイズより大きいときリクエストエラーとして処理する関数を追加しました。
リクエストヘッダーのパースが終了した時点でconfigの情報を確認したいため、Transactionでconfigへのポインターをメンバとして持つ形にしています。
リクエストエラーの例外がステータスコードを持つように変更しています。
ステータスコードに合わせたレスポンスの生成はまた別のプルリクで行う予定です。

client max body size対応

---

integration_test/tester/client.go
integration_test/tests/TestAutoindex.go
integration_test/tests/TestBadRequest.go
integration_test/tests/TestCgi.go
integration_test/tests/TestDELETE.go
integration_test/tests/TestIOMulti.go
integration_test/tests/TestLimitExpect.go
integration_test/tests/TestLocation.go
integration_test/tests/TestServerName.go
integration_test/tests/testGET.go
integration_test/tests/utils/fileio.go
integration_test/tests/utils/runWebserv.go

現状, fileToBytesとNewClientに関して, エラー時にexitするようにしました。
exit用に関数を用意して, killwebservしてからexitしています。
killwebservのパッケージはtestsではなく独立したパッケージにするかもです。
とりあえずこれで問題なければ他のerror部分もそうすると思います。
エラーがあるとこんな感じです。

itestでエラー時にexitする

---

.github/pre-push
srcs/event/Connection.cpp
srcs/event/Connection.hpp
srcs/event/Request.cpp
srcs/event/Request.hpp
srcs/event/Response.hpp
srcs/event/Server.cpp

良い感じのリファクタリングありがとうございます
sendのstateの管理をResponseに責任を持たせるようにしてみました。
send_responseを
send_response_queue_front
に変更し、queueを扱っていることをわかりやすくしてみました。
queueの管理と__last_event_time_のみ行うようにしました。

send後の処理をresponse側へ

---

srcs/http/response/ResponseGen_cgi.cpp
srcs/utils/file_io_utils.cpp
srcs/utils/file_io_utils.hpp

Resultを継承したクラスErrorとOkを追加しました。
Resultを返す関数を実装するときは返り値としてErrorかOkを使うことで引数のミスなどを防げると思います。
受け取る側の使い方はこれまでと変わりません。

Error, Ok追加

---

integration_test/go.mod
integration_test/httptest/checker.go
integration_test/tests/TestMultiConnection.go
integration_test/tests/generate.go

#491 の内容を分割しました。
この先変更されると思いますが, ひとまず複数クライアントからの同時接続のテストの雛形です。

multi connectionのテストを追加

---

integration_test/httpresp/body.go
integration_test/tests/TestReturn.go
srcs/event/Request.cpp
srcs/event/Request.hpp
srcs/http/response/ResponseGenerator.cpp
srcs/http/response/ResponseGenerator.hpp

- is_error_status_code()のエラーコード条件を299から上でなく399より上に変更してしまいましたが問題ありませんか？
- respose_message()ではbodyを引数で渡していて, error時はerror用のbodyを作成していますが,  
error時もそうで無い時もresponse_messsage()内でbodyを作るか,  
error時もそうで無い時もrpesponse_message()に入る前にbodyを作るかに統一したほうが良いかなと思っています。

respose_message()とgenerate_error_message()を統合

---

srcs/socket/CgiSocket.cpp

kill()がsignal.hをincludeしないとコンパイルできなかったので追加しました。
ただ以前はコンパイルできていた気がするのでおかしいなと思っています。
おおくぼさんのmacはコンパイルできますか？

include <signal.h>
